# Cleaning Dataset

## Importing Libraries

In [1]:
import pandas as pd
import numpy as np

## Importing Dataset

In [2]:
data = pd.read_csv("../data/raw/full_dataset.csv")
geolocation = pd.read_csv("../data/raw/olist_geolocation_dataset.csv")

display(data.head())
display(geolocation.head())

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,delivered_late,product_category_name_english,handoff_delay,is_first_time_buyer,is_canceled
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,False,housewares,2.0,False,False
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,False,housewares,2.0,False,False
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,False,housewares,2.0,False,False
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50,False,perfumery,0.0,True,False
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,5.0,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:58,False,auto,0.0,True,False

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

## Merging Datasets with GeoLocation

In [3]:
geo_avg = (
    geolocation.groupby("geolocation_zip_code_prefix")[["geolocation_lat", "geolocation_lng"]]
    .mean()
    .reset_index()
)

geo_customer = geo_avg.rename(columns={
    "geolocation_zip_code_prefix": "customer_zip_code_prefix",
    "geolocation_lat": "customer_lat",
    "geolocation_lng": "customer_lng"
})


data = data.merge(geo_customer, on="customer_zip_code_prefix", how="inner")

geo_seller = geo_avg.rename(columns={
    "geolocation_zip_code_prefix": "seller_zip_code_prefix",
    "geolocation_lat": "seller_lat",
    "geolocation_lng": "seller_lng"
})

data = data.merge(geo_seller, on="seller_zip_code_prefix", how="inner")

data.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,review_answer_timestamp,delivered_late,product_category_name_english,handoff_delay,is_first_time_buyer,is_canceled,customer_lat,customer_lng,seller_lat,seller_lng
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,2017-10-12 03:43:48,False,housewares,2.0,False,False,-23.576983,-46.587161,-23.680729,-46.444238
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,2017-10-12 03:43:48,False,housewares,2.0,False,False,-23.576983,-46.587161,-23.680729,-46.444238
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,2017-10-12 03:43:48,False,housewares,2.0,False,False,-23.576983,-46.587161,-23.680729,-46.444238
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,2018-08-08 18:37:50,False,perfumery,0.0,True,False,-12.177924,-44.660711,-19.807681,-43.980427
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,2018-08-22 19:07:58,False,auto,0.0,True,False,-16.745150,-48.514783,-21.363502,-48.229601

In [4]:
def haversine(lat1, lng1, lat2, lng2):
    # convert degrees to radians
    lat1, lng1, lat2, lng2 = map(np.radians, [lat1, lng1, lat2, lng2])
    
    dlat = lat2 - lat1
    dlng = lng2 - lng1
    
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlng/2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    r = 6371  # Radius of Earth in kilometers
    return c * r

data["distance_km"] = haversine(
    data["customer_lat"], data["customer_lng"],
    data["seller_lat"], data["seller_lng"]
)

In [5]:
display(data.columns)
display(data.shape)

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'customer_unique_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'seller_zip_code_prefix', 'seller_city', 'seller_state',
       'payment_sequential', 'payment_type', 'payment_installments',
       'payment_value', 'review_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp', 'delivered_late',
       'product_category_name_english', 'handoff_delay', 'is_first_time_buyer',
       'is_canceled', 'customer_lat', 'customer_lng', 'seller_lat',
       'seller_lng', 'distance_km'],
      dtype='object')

(116635, 49)

## Pre-Processing Data Columns

### Removing Unnecessary Columns

In [6]:
# Rename the incorrect column name
data.rename(columns={"product_name_lenght": "product_name_length",
                     'product_description_lenght': 'product_description_length',
                     }, inplace=True)

data.drop(columns=['review_comment_title',
                   'review_comment_message',
                   'review_creation_date',
                   'review_answer_timestamp',
                   'product_category_name',
                   'payment_sequential',
                   'payment_type',
                   'payment_installments',
                   'payment_value'], inplace=True)

display(data.columns)

display(data.shape)

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'customer_unique_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'product_name_length',
       'product_description_length', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'seller_zip_code_prefix', 'seller_city', 'seller_state', 'review_id',
       'review_score', 'delivered_late', 'product_category_name_english',
       'handoff_delay', 'is_first_time_buyer', 'is_canceled', 'customer_lat',
       'customer_lng', 'seller_lat', 'seller_lng', 'distance_km'],
      dtype='object')

(116635, 40)

### Removing Timestamps and Only Keeping Dates

In [7]:
datetime_columns = [
    'order_purchase_timestamp', 'order_approved_at',
    'order_delivered_carrier_date', 'order_delivered_customer_date',
    'order_estimated_delivery_date', 'shipping_limit_date'
]

# Convert to datetime and strip time (keep only date)
for col in datetime_columns:
    if col in data.columns:
        data[col] = pd.to_datetime(data[col]).dt.date

# Display to verify changes
data.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,delivered_late,product_category_name_english,handoff_delay,is_first_time_buyer,is_canceled,customer_lat,customer_lng,seller_lat,seller_lng,distance_km
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02,2017-10-02,2017-10-04,2017-10-10,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,False,housewares,2.0,False,False,-23.576983,-46.587161,-23.680729,-46.444238,18.576110
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02,2017-10-02,2017-10-04,2017-10-10,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,False,housewares,2.0,False,False,-23.576983,-46.587161,-23.680729,-46.444238,18.576110
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02,2017-10-02,2017-10-04,2017-10-10,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,False,housewares,2.0,False,False,-23.576983,-46.587161,-23.680729,-46.444238,18.576110
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24,2018-07-26,2018-07-26,2018-08-07,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,False,perfumery,0.0,True,False,-12.177924,-44.660711,-19.807681,-43.980427,851.495069
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08,2018-08-08,2018-08-08,2018-08-17,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,False,auto,0.0,True,False,-16.745150,-48.514783,-21.363502,-48.229601,514.410666

### Creating Custom Columns

In [8]:
# Convert both columns to datetime64[ns] before subtraction
data['handoff_delay'] = (
    pd.to_datetime(data['order_delivered_carrier_date']) -
    pd.to_datetime(data['shipping_limit_date'])
).dt.days

data['delivery_delay'] = (
    pd.to_datetime(data['order_delivered_customer_date']) -
    pd.to_datetime(data['order_estimated_delivery_date'])
).dt.days

# Delivered late remains a boolean comparison
data['delivered_late'] = (
    pd.to_datetime(data['order_delivered_customer_date']) >
    pd.to_datetime(data['order_estimated_delivery_date'])
)

# Preview the results
display(data.head())

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,product_category_name_english,handoff_delay,is_first_time_buyer,is_canceled,customer_lat,customer_lng,seller_lat,seller_lng,distance_km,delivery_delay
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02,2017-10-02,2017-10-04,2017-10-10,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,housewares,-2.0,False,False,-23.576983,-46.587161,-23.680729,-46.444238,18.576110,-8.0
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02,2017-10-02,2017-10-04,2017-10-10,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,housewares,-2.0,False,False,-23.576983,-46.587161,-23.680729,-46.444238,18.576110,-8.0
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02,2017-10-02,2017-10-04,2017-10-10,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,housewares,-2.0,False,False,-23.576983,-46.587161,-23.680729,-46.444238,18.576110,-8.0
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24,2018-07-26,2018-07-26,2018-08-07,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,perfumery,-4.0,True,False,-12.177924,-44.660711,-19.807681,-43.980427,851.495069,-6.0
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08,2018-08-08,2018-08-08,2018-08-17,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,auto,-5.0,True,False,-16.745150,-48.514783,-21.363502,-48.229601,514.410666,-18.0

In [9]:
display(data.columns)
display(data.shape)

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'customer_unique_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'product_name_length',
       'product_description_length', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'seller_zip_code_prefix', 'seller_city', 'seller_state', 'review_id',
       'review_score', 'delivered_late', 'product_category_name_english',
       'handoff_delay', 'is_first_time_buyer', 'is_canceled', 'customer_lat',
       'customer_lng', 'seller_lat', 'seller_lng', 'distance_km',
       'delivery_delay'],
      dtype='object')

(116635, 41)

### Removing Duplicate Rows

In [10]:
# Remove fully duplicated rows
data.drop_duplicates(inplace=True)

# Reset index after dropping duplicates
data.reset_index(drop=True, inplace=True)

# Display updated DataFrame
display(data.head())
display(data.shape)
display(data.columns)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,product_category_name_english,handoff_delay,is_first_time_buyer,is_canceled,customer_lat,customer_lng,seller_lat,seller_lng,distance_km,delivery_delay
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02,2017-10-02,2017-10-04,2017-10-10,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,housewares,-2.0,False,False,-23.576983,-46.587161,-23.680729,-46.444238,18.576110,-8.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24,2018-07-26,2018-07-26,2018-08-07,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,perfumery,-4.0,True,False,-12.177924,-44.660711,-19.807681,-43.980427,851.495069,-6.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08,2018-08-08,2018-08-08,2018-08-17,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,auto,-5.0,True,False,-16.745150,-48.514783,-21.363502,-48.229601,514.410666,-18.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18,2017-11-18,2017-11-22,2017-12-02,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,...,pet_shop,-1.0,True,False,-5.774190,-35.271143,-19.837682,-43.924053,1822.226336,-13.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13,2018-02-13,2018-02-14,2018-02-16,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,stationery,-5.0,True,False,-23.676370,-46.514627,-23.543395,-46.262086,29.676625,-10.0

(111717, 41)

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'customer_unique_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'product_name_length',
       'product_description_length', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'seller_zip_code_prefix', 'seller_city', 'seller_state', 'review_id',
       'review_score', 'delivered_late', 'product_category_name_english',
       'handoff_delay', 'is_first_time_buyer', 'is_canceled', 'customer_lat',
       'customer_lng', 'seller_lat', 'seller_lng', 'distance_km',
       'delivery_delay'],
      dtype='object')

## Re-Ordering Columns

In [11]:
# Define the final desired column order based on your prior instructions and the current columns
final_column_order = [
    # Order and Customer Metadata
    'order_id', 'order_item_id', 'order_status', 'order_purchase_timestamp',
    'order_approved_at', 'order_estimated_delivery_date', 'is_canceled',
    
    # Customer Information
    'customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
    'customer_city', 'customer_state', 'customer_lat', 'customer_lng',
    'order_delivered_customer_date', 'is_first_time_buyer',
    
    # Seller Information
    'seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state',
    'seller_lat', 'seller_lng', 'shipping_limit_date',
    'order_delivered_carrier_date', 'handoff_delay',
    
    # Distance Between Seller and Customer
    'distance_km',
    
    # Product Information
    'product_id', 'product_category_name_english', 'price', 'freight_value',
    'product_name_length', 'product_description_length', 'product_photos_qty',
    'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm',
    
    # Review Information
    'review_id', 'review_score',
    
    # Delivery Delay Information
    'delivered_late', 'delivery_delay'
]

# Reorder the columns
data = data[final_column_order]

display(data.head())
display(data.shape)
display(data.columns)

,order_id,order_item_id,order_status,order_purchase_timestamp,order_approved_at,order_estimated_delivery_date,is_canceled,customer_id,customer_unique_id,customer_zip_code_prefix,...,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,review_id,review_score,delivered_late,delivery_delay
0,e481f51cbdc54678b7cc49136f2d6af7,1.0,delivered,2017-10-02,2017-10-02,2017-10-18,False,9ef432eb6251297304e76186b10a928d,7c396fd4830fd04220f754e42b4e5bff,3149,...,268.0,4.0,500.0,19.0,8.0,13.0,a54f0611adc9ed256b57ede6b6eb5114,4.0,False,-8.0
1,53cdb2fc8bc7dce0b6741e2150273451,1.0,delivered,2018-07-24,2018-07-26,2018-08-13,False,b0830fb4747a6c6d20dea0b8c802d7ef,af07308b275d755c9edb36a90c618231,47813,...,178.0,1.0,400.0,19.0,13.0,19.0,8d5266042046a06655c8db133d120ba5,4.0,False,-6.0
2,47770eb9100c2d0c44946d9cf07ec65d,1.0,delivered,2018-08-08,2018-08-08,2018-09-04,False,41ce2a54c0b03bf3443c3d931a367089,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,232.0,1.0,420.0,24.0,19.0,21.0,e73b67b67587f7644d5bd1a52deb1b01,5.0,False,-18.0
3,949d5b44dbf5de918fe9c16f97b45f8a,1.0,delivered,2017-11-18,2017-11-18,2017-12-15,False,f88197465ea7920adcdbec7375364d82,7c142cf63193a1473d2e66489a9ae977,59296,...,468.0,3.0,450.0,30.0,10.0,20.0,359d03e676b3c069f62cadba8dd3f6e8,5.0,False,-13.0
4,ad21c59c0840e6cb83a9ceb5573f8159,1.0,delivered,2018-02-13,2018-02-13,2018-02-26,False,8ab97904e6daea8866dbdbc4fb7aad2c,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,316.0,4.0,250.0,51.0,15.0,15.0,e50934924e227544ba8246aeb3770dd4,5.0,False,-10.0

(111717, 41)

Index(['order_id', 'order_item_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_estimated_delivery_date', 'is_canceled',
       'customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state', 'customer_lat', 'customer_lng',
       'order_delivered_customer_date', 'is_first_time_buyer', 'seller_id',
       'seller_zip_code_prefix', 'seller_city', 'seller_state', 'seller_lat',
       'seller_lng', 'shipping_limit_date', 'order_delivered_carrier_date',
       'handoff_delay', 'distance_km', 'product_id',
       'product_category_name_english', 'price', 'freight_value',
       'product_name_length', 'product_description_length',
       'product_photos_qty', 'product_weight_g', 'product_length_cm',
       'product_height_cm', 'product_width_cm', 'review_id', 'review_score',
       'delivered_late', 'delivery_delay'],
      dtype='object')

## Export to CSV

In [12]:
data.to_csv("../data/cleaned/cleaned_dataset.csv", index=False)